### ISSUE TITLE
Question about ActiveRecord integration

### ISSUE THREAD

**Issue by ijin** [degica/voynich#9]
It is my understanding that when reading encrypted data through `model.secret_data`,  `kms_client.decrypt` is called, which makes an API request to AWS.

Since the KMS API has a limit of 100 queries/sec, do you not recommend using this for high traffic sites?

In this case, I was wondering if it would be better to decrypt a secret key through KMS in the Rails initializer, and use this for AES decryption per request.

**Comment by k2nr** [comment]
ActiveRecord integration doesn't cache decrypted data keys so if your site exceeds the KMS limit 100req/sec you can't use the active record integration. As you said it is possible to keep a plaintext data key in the rails process but you have to take into account security trade off; Amazon recommends erasing a plaintext data key after using it http://docs.aws.amazon.com/kms/latest/APIReference/API_GenerateDataKey.html

**Comment by ijin** [comment]
Thanks for confirming about the non-caching behavior. Looks like I'll have to make careful design decisions on where to use this.

Yes, I understand that there is a tradeoff in performance vs security. This seems to have been discussed in the forums as well (https://forums.aws.amazon.com/thread.jspa?threadID=200236&tstart=50).

As a middleground, I'll try to see if I can get the decrypted data key on the first request, and then cache it for a couple of minutes which will be discarded thereafter. That way the rate limit will be reduced, provided that I use a single data key for a single domain model, and the decrypted data keys would not exist during idle time.
